module.exports = {

    rounds: "Rounds",
    wins: "Wins",
    kd: "KD",
    kda: "KDA",
    winPercent: "Win %",
    avgRank: "Avg Rank",
    top10Ratio: "Top 10 %",
    adr: "ADR",
    currentRankPoint: "Rank Points",
    currentTier_Tier: "Tier",
    currentTier_subTier: "SubTier",
    winRate: "Win %",
    timeSurvived: "Time Survived",
    hsRatio: "Headshot %",
    suicides: "Suicides",
    teamkills: "Team Kills",
    longestKill: "Longest Kill",
    NewRating: "Rat Rating",
    OldRating: "Fragger Rating",
    squadfpp: "FPP Squad",
    squad: "TPP Squad",
    solofpp: "FPP Solo",
    solo: "TPP Solo",
    duofpp: "FPP Duo",
    duo: "TPP Duo",
    steam: "Steam",
    psn: "Playstation",
    xbox: "Xbox",
    stadia: "Stadia",
    kakao: "Kakao",
}